[project]
name = "de-streaming"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lateeeppp", email = "ikhsannudin.dev@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.43.108",
    "dbt-athena>=1.11.1",
    "ruff>=0.16.10",
    "sqlfmt>=0.0.3",
    "websocket-client>=1.9.2",
    "websockets>=17.1",
]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes (unused imports, undefined variables)
    "I",    # isort (import ordering)
    "UP",   # pyupgrade (modern python syntax)
    "B",    # flake8-bugbear
    "BLE",  # flake8-blind-except
]
ignore = [
    "E501", # line-length (ditangani otomatis oleh ruff format)
]
